### ISSUE TITLE
导入以后，运行显示error:模板目录或者编译目录或者缓存目录不存在！请添加!!

### ISSUE THREAD

**Issue by xuzeyu** [itcuijian/novel#2]
如题，http://192.168.1.162/novel/，访问以后显示错误，error:模板目录或者编译目录或者缓存目录不存在！请添加!!   加入这几个文件夹，又显示error:生成编译文件失败！

**Comment by itcuijian** [comment]
你添加的那几个文件夹有没有写入权限？？你单独执行一下file_put_contents函数看看会不会报错！

**Comment by tiev0li** [comment]
手动创建文件夹可以访问使用
